services:
  check-config:
    container_name: check-config
    image: alpine:latest
    command: /vana/container-scripts/check-config.sh
    volumes:
      - .:/vana:ro
    environment:
      - NETWORK
      - WITHDRAWAL_ADDRESS
      - DEPOSIT_RPC_URL
      - DEPOSIT_CONTRACT_ADDRESS
      - DEPOSIT_PRIVATE_KEY
      - USE_VALIDATOR=${USE_VALIDATOR:-false}
    depends_on:
      geth-init:
        condition: service_completed_successfully
      jwt-gen:
        condition: service_completed_successfully
      prysm-keygen:
        condition: service_completed_successfully
    profiles: ["init", "execution", "node", "validator", "manual"]

  # delete-all:
  #   container_name: delete-all
  #   image: alpine:latest
  #   command: sh -c "rm -rf /vana/data/* /vana/data/.[!.]* /vana/data/..?*"
  #   volumes:
  #     - ./data:/vana/data
  #   profiles: ["delete"]

  delete-all:
    container_name: delete-all
    image: alpine:latest
    command: echo "All data deleted"
    depends_on:
      delete-geth:
        condition: service_completed_successfully
      delete-prysm:
        condition: service_completed_successfully
      delete-lighthouse:
        condition: service_completed_successfully
    profiles: ["delete"]

  delete-geth:
    container_name: delete-geth
    image: alpine:latest
    command: rm -rf /vana/execution/geth
    volumes:
      - ./data/geth:/vana/execution
    profiles: ["delete"]

  delete-prysm:
    container_name: delete-prysm
    image: alpine:latest
    command: rm -rf /vana/prysm/beacondata /vana/prysm/validatordata
    volumes:
      - ./data/prysm:/vana/prysm
    profiles: ["delete"]

  # There is also: The --purge-db flag can be used to permanently delete the existing data directory.
  delete-lighthouse:
    container_name: delete-lighthouse
    image: alpine:latest
    command: rm -rf /vana/lighthouse/beacon /vana/lighthouse/validators
    volumes:
      - ./data/lighthouse:/vana/lighthouse
    profiles: ["delete"]

  jwt-gen:
    container_name: jwt-gen
    image: alpine:latest
    command: >
      sh -c '
      apk add -q openssl &&
      openssl rand -hex 32 | tr -d "\n" > /vana/jwt.hex &&
      chmod 600 /vana/jwt.hex'
    volumes:
      - ./data:/vana
    profiles: ["init"]

  geth-init:
    container_name: geth-init
    image: ethereum/client-go:latest
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "if [ ! -d /vana/geth/geth/chaindata ]; then
         echo 'Initializing geth...';
         geth --state.scheme=${GETH_STATE_SCHEME:-path} --datadir=/vana/geth init /vana/geth/genesis.json;
         echo 'Geth initialized';
       else
         echo 'Geth already initialized';
       fi"
    volumes:
      - ./data/geth:/vana/geth
      - ./networks/${NETWORK}/genesis.json:/vana/geth/genesis.json:ro
    profiles: ["init"]

  prysm-keygen:
    container_name: prysm-keygen
    image: alpine:latest
    command: >
      sh -c '
      apk add -q openssl &&
      openssl rand -hex 32 | tr -d "\n" > /vana/prysm/prysm-key.hex &&
      chmod 600 /vana/prysm/prysm-key.hex'
    volumes:
      - ./data/prysm:/vana/prysm
    profiles: ["init"]

  validator-keygen:
    container_name: validator-setup
    build:
      context: https://github.com/vana-com/staking-deposit-cli.git#vana-main
      dockerfile: Dockerfile
    entrypoint: "/vana/container-scripts/validator-keygen.sh"
    volumes:
      - ./secrets:/app/validator_keys
      - ./container-scripts:/vana/container-scripts
    environment:
      - NUM_VALIDATORS
      - WITHDRAWAL_ADDRESS
      - NETWORK
      - LANGUAGE
    profiles: ["manual"]

  submit-deposits:
    container_name: submit-deposits
    image: ghcr.io/foundry-rs/foundry:latest
    volumes:
      - ./secrets:/validator_keys
    environment:
      - DEPOSIT_RPC_URL
      - DEPOSIT_CONTRACT_ADDRESS
      - DEPOSIT_PRIVATE_KEY
    entrypoint: ["sh", "-c"]
    command:
      - |
        apk add --no-cache --quiet jq
        for file in /validator_keys/deposit_data-*.json; do
          PUBKEY=$(jq -r '.[0].pubkey' "$$file")
          WITHDRAWAL_CREDENTIALS=$(jq -r '.[0].withdrawal_credentials' "$$file")
          SIGNATURE=$(jq -r '.[0].signature' "$$file")
          DEPOSIT_DATA_ROOT=$(jq -r '.[0].deposit_data_root' "$$file")
          cast send $$DEPOSIT_CONTRACT_ADDRESS \
            "deposit(bytes,bytes,bytes,bytes32)" \
            "0x$$PUBKEY" \
            "0x$$WITHDRAWAL_CREDENTIALS" \
            "0x$$SIGNATURE" \
            "0x$$DEPOSIT_DATA_ROOT" \
            --value 35000ether \
            --private-key $$DEPOSIT_PRIVATE_KEY \
            --rpc-url $$DEPOSIT_RPC_URL
        done
    depends_on:
      check-config:
        condition: service_completed_successfully
    profiles: ["manual"]

  ### Geth

  geth:
    container_name: geth
    image: ethereum/client-go:latest
    command:
      - --verbosity=3  # 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail
      - --nat=extip:${EXTERNAL_IP}
      - --datadir=/root/.ethereum
      - --networkid=${CHAIN_ID}
      - --http
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=${HTTP_PORT:-8545}
      - --http.api=eth,net,web3,personal,admin
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=${AUTHRPC_PORT:-8551}
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.vhosts=*
      - --syncmode=${GETH_SYNCMODE:-full}
      - --state.scheme=${GETH_STATE_SCHEME:-path}
      - --gcmode=${GETH_GCMODE:-full}
      - --port=${P2P_PORT:-30303}
      - --bootnodes=${GETH_BOOTNODES}
    ports:
      - "${AUTHRPC_PORT:-8551}:${AUTHRPC_PORT:-8551}"
      - "${HTTP_PORT:-8545}:${HTTP_PORT:-8545}"
      - "${P2P_PORT:-30303}:${P2P_PORT:-30303}"
    volumes:
      - ./data/geth:/root/.ethereum  # Use the default so that the default ipc path works, etc.
      - ./data/jwt.hex:/root/.ethereum/jwt.hex:ro
    depends_on:
      geth-init:
        condition: service_completed_successfully
      jwt-gen:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
    profiles: ["execution", "node", "validator"]

  ### Prysm

  prysm-beacon:
    container_name: prysm-beacon
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    command:
      - --accept-terms-of-use
      - --chain-id=${CHAIN_ID}
      - --verbosity=info
      - --min-sync-peers=1
      - --block-batch-limit=${PRYSM_BLOCK_BATCH_LIMIT:-256}
      - --block-batch-limit-burst-factor=${PRYSM_BLOCK_BATCH_LIMIT_BURST_FACTOR:-8}
      - --blob-batch-limit=${PRYSM_BLOB_BATCH_LIMIT:-256}
      - --blob-batch-limit-burst-factor=${PRYSM_BLOB_BATCH_LIMIT_BURST_FACTOR:-8}
      - --datadir=/vana/prysm/beacondata
      - --genesis-state=/vana/prysm/genesis.ssz
      - --chain-config-file=/vana/prysm/config.yml
      - --execution-endpoint=http://geth:${AUTHRPC_PORT:-8545}
      - --jwt-secret=/vana/jwt.hex
      - --rpc-host=0.0.0.0
      - --rpc-port=${RPC_PORT:-4000}
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=${GRPC_GATEWAY_PORT:-3500}
      - --p2p-host-ip=${EXTERNAL_IP}
      - --bootstrap-node=${PRYSM_PEER_1}
      - --peer=${PRYSM_PEER_1}
      - --peer=${PRYSM_PEER_2}
      - --peer=${PRYSM_PEER_3}
      - --peer=${PRYSM_PEER_4}
      - --peer=${PRYSM_PEER_5}
      - --p2p-priv-key=/vana/prysm/prysm-key.hex
      - --suggested-fee-recipient=${WITHDRAWAL_ADDRESS}
      - --slots-per-archive-point=${PRYSM_SLOTS_PER_ARCHIVE_POINT:-512}
    depends_on:
      geth:
        condition: service_started
      prysm-keygen:
        condition: service_completed_successfully
      jwt-gen:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
    ports:
      - "${RPC_PORT:-4000}:${RPC_PORT:-4000}"
      - "${GRPC_GATEWAY_PORT:-3500}:${GRPC_GATEWAY_PORT:-3500}"
      - "${P2P_TCP_PORT:-13000}:${P2P_TCP_PORT:-13000}"
      - "${P2P_UDP_PORT:-12000}:${P2P_UDP_PORT:-12000}/udp"
    environment:
      - WITHDRAWAL_ADDRESS
      - PRYSM_SLOTS_PER_ARCHIVE_POINT
      - PRYSM_BLOCK_BATCH_LIMIT
      - PRYSM_BLOCK_BATCH_LIMIT_BURST_FACTOR
      - PRYSM_BLOB_BATCH_LIMIT
      - PRYSM_BLOB_BATCH_LIMIT_BURST_FACTOR
    volumes:
      - ./data/jwt.hex:/vana/jwt.hex:ro
      - ./data/prysm:/vana/prysm
      - ./networks/${NETWORK}/genesis.ssz:/vana/prysm/genesis.ssz:ro
      - ./networks/${NETWORK}/config.yml:/vana/prysm/config.yml:ro
    profiles: ["prysm", "validator"]

  prysm-import-keys:
    container_name: prysm-import-keys
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    command:
      - accounts
      - import
      - --accept-terms-of-use
      - --keys-dir=/vana/secrets
      - --wallet-dir=/vana/wallet
      - --account-password-file=/vana/secrets/account_password.txt
      - --wallet-password-file=/vana/secrets/wallet_password.txt
    volumes:
      - ./secrets:/vana/secrets:ro
      - ./data/prysm/wallet:/vana/wallet
    # Re-enable if validator-keygen can be automated
    # depends_on:
    #   validator-keygen:
    #     condition: service_completed_successfully
    profiles: ["prysm", "validator"]

  prysm-validator:
    container_name: prysm-validator
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    command:
      - --accept-terms-of-use
      - --verbosity=info
      - --beacon-rpc-provider=${EXTERNAL_IP}:${RPC_PORT:-4000}
      - --beacon-rest-api-provider=${EXTERNAL_IP}:${RPC_PORT:-4000}
      - --datadir=/vana/validator
      - --wallet-dir=/vana/wallet
      - --wallet-password-file=/vana/secrets/wallet_password.txt
      - --chain-config-file=/vana/prysm/config.yml
      - --suggested-fee-recipient=${WITHDRAWAL_ADDRESS}
      - --rpc-port=${VALIDATOR_PORT:-7000}
    depends_on:
      prysm-beacon:
        condition: service_started
      prysm-import-keys:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
    ports:
      - "${VALIDATOR_PORT:-7000}:${VALIDATOR_PORT:-7000}"
    environment:
      - WITHDRAWAL_ADDRESS
    volumes:
      - ./data/prysm:/vana/validator
      - ./data/prysm/wallet:/vana/wallet
      - ./secrets:/vana/secrets:ro
      - ./networks/${NETWORK}/config.yml:/vana/prysm/config.yml:ro
    profiles: ["prysm", "validator"]

  ### Lighthouse

  lighthouse-beacon:
    container_name: lighthouse-beacon
    image: sigp/lighthouse:latest
    command:
      - lighthouse
      - beacon_node
      - --testnet-dir=/vana/network
      # - --network=${NETWORK}
      - --datadir=/vana/lighthouse
      - --execution-endpoint=http://geth:${AUTHRPC_PORT:-8551}
      - --execution-jwt=/vana/jwt.hex
      - --http
      - --http-address=0.0.0.0
      - --http-port=${RPC_PORT:-4000}
      - --port=${P2P_TCP_PORT:-13000}
      - --discovery-port=${P2P_UDP_PORT:-12000}
      - --suggested-fee-recipient=${WITHDRAWAL_ADDRESS}
      # - --checkpoint-sync-url=${CHECKPOINT_SYNC_URL:-}
      - --boot-nodes=${LIGHTHOUSE_BOOT_NODES:-}
      # - --target-peers=${TARGET_PEERS:-50}
      # - --execution-timeout-multiplier=${EXECUTION_TIMEOUT_MULTIPLIER:-1}
      - --disable-deposit-contract-sync
      - --allow-insecure-genesis-sync
    depends_on:
      geth:
        condition: service_started
      jwt-gen:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
    ports:
      - "${RPC_PORT:-4000}:${RPC_PORT:-4000}"
      - "${P2P_TCP_PORT:-13000}:${P2P_TCP_PORT:-13000}"
      - "${P2P_UDP_PORT:-12000}:${P2P_UDP_PORT:-12000}/udp"
    environment:
      - NETWORK
      - WITHDRAWAL_ADDRESS
      # - CHECKPOINT_SYNC_URL
      - LIGHTHOUSE_BOOT_NODES
      # - TARGET_PEERS
      # - EXECUTION_TIMEOUT_MULTIPLIER
    volumes:
      - ./data/jwt.hex:/vana/jwt.hex:ro
      - ./data/lighthouse:/vana/lighthouse
      - ./networks/${NETWORK}/genesis.json:/vana/network/genesis.json:ro
      - ./networks/${NETWORK}/genesis.ssz:/vana/network/genesis.ssz:ro
      - ./networks/${NETWORK}/lighthouse/config.yml:/vana/network/config.yaml:ro
      - ./networks/${NETWORK}/lighthouse/deposit_contract_block.txt:/vana/network/deposit_contract_block.txt:ro
    profiles: ["lighthouse", "node", "validator"]

  # lighthouse-validator-manager:
  #   container_name: lighthouse-validator-manager
  #   image: sigp/lighthouse:latest
  #   volumes:
  #     - ./data/lighthouse:/root/.lighthouse
  #     - ./secrets:/root/secrets
  #   environment:
  #     - NETWORK
  #     - WITHDRAWAL_ADDRESS
  #   entrypoint:
  #     - sh
  #     - -c
  #     - |
  #       lighthouse validator-manager create \
  #         --network ${NETWORK} \
  #         --first-index 0 \
  #         --count ${NUM_VALIDATORS:-1} \
  #         --eth1-withdrawal-address ${WITHDRAWAL_ADDRESS} \
  #         --suggested-fee-recipient ${WITHDRAWAL_ADDRESS} \
  #         --output-path /root/secrets
  #   profiles: ["lighthouse", "manual"]

  lighthouse-import-keys:
    container_name: lighthouse-import-keys
    image: sigp/lighthouse:latest
    command:
      - lighthouse
      # - --network=${NETWORK}
      - account
      - validator
      - import
      - --directory=/vana/secrets
      - --datadir=/vana/validator/lighthouse
    volumes:
      - ./secrets:/vana/secrets:ro
      - ./data/lighthouse:/vana/validator/lighthouse
    # Re-enable if validator-keygen can be automated
    # depends_on:
    #   validator-keygen:
    #     condition: service_completed_successfully
    profiles: ["manual"]
    # profiles: ["lighthouse", "validator"]

  lighthouse-validator:
    container_name: lighthouse-validator
    image: sigp/lighthouse:latest
    command:
      - lighthouse
      # - --network=${NETWORK}
      - validator_client
      - --testnet-dir=/vana/network
      - --beacon-nodes=http://lighthouse-beacon:${RPC_PORT:-4000}
      - --datadir=/vana/validator/lighthouse
      - --suggested-fee-recipient=${WITHDRAWAL_ADDRESS}
    depends_on:
      lighthouse-beacon:
        condition: service_started
      check-config:
        condition: service_completed_successfully
    environment:
      - WITHDRAWAL_ADDRESS
    volumes:
      - ./data/lighthouse:/vana/validator/lighthouse
      - ./secrets:/vana/secrets:ro
      - ./networks/${NETWORK}/genesis.json:/vana/network/genesis.json:ro
      - ./networks/${NETWORK}/genesis.ssz:/vana/network/genesis.ssz:ro
      - ./networks/${NETWORK}/lighthouse/config.yml:/vana/network/config.yaml:ro
      - ./networks/${NETWORK}/lighthouse/deposit_contract_block.txt:/vana/network/deposit_contract_block.txt:ro
    profiles: ["lighthouse", "validator"]
