x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "5"
      compress: "true"

services:
  # Initialization services
  jwt-gen:
    <<: *default-logging
    image: alpine:latest
    container_name: jwt-gen
    volumes:
      - ./data:/vana
    command: >
      sh -c '
      if [ ! -f /vana/jwt.hex ]; then
        apk add --update -q openssl &&
        openssl rand -hex 32 | tr -d "\n" > /vana/jwt.hex &&
        chmod 600 /vana/jwt.hex
        echo "JWT file generated"
      else
        echo "JWT file already exists"
      fi'
    profiles: ["init"]

  geth-init:
    <<: *default-logging
    image: ethereum/client-go:${GETH_VERSION:-latest}
    container_name: geth-init
    volumes:
      - ./data/execution:/vana/execution
      - ./networks/${NETWORK}/genesis.json:/vana/execution/genesis.json:ro
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "if [ ! -d /vana/execution/geth/chaindata ]; then
         echo 'Initializing geth...';
         geth --state.scheme=${GETH_STATE_SCHEME:-path} --datadir=/vana/execution init /vana/execution/genesis.json;
         echo 'Geth initialized';
       else
         echo 'Geth already initialized';
       fi"
    profiles: ["init"]

  prysm-keygen:
    <<: *default-logging
    image: alpine:latest
    container_name: prysm-keygen
    volumes:
      - ./data/consensus:/vana/consensus
    command: >
      sh -c '
      if [ ! -f /vana/consensus/prysm-key.hex ]; then
        apk add -q openssl &&
        openssl rand -hex 32 | tr -d "\n" > /vana/consensus/prysm-key.hex &&
        chmod 600 /vana/consensus/prysm-key.hex
        echo "Prysm key generated"
      else
        echo "Prysm key already exists"
      fi'
    profiles: ["init"]

  bootnode-init:
    <<: *default-logging
    image: ethereum/client-go:${GETH_ALLTOOLS_VERSION:-alltools-latest}
    container_name: bootnode-init
    volumes:
      - ./data/execution:/vana/execution
    command: >
      sh -c '
      if [ ! -f /vana/execution/bootnode.key ]; then
        bootnode -genkey /vana/execution/bootnode.key &&
        chmod 600 /vana/execution/bootnode.key
        echo "Bootnode key generated"
      else
        echo "Bootnode key already exists"
      fi'
    profiles: ["init"]

  check-config:
    <<: *default-logging
    image: alpine:latest
    container_name: check-config
    volumes:
      - .:/vana:ro
      # Uncomment this when we have a better way to manage keys apart from secrets/.
      # - /vana/secrets  # Create an empty volume, effectively hiding ./secrets
    environment:
      - NETWORK
      - WITHDRAWAL_ADDRESS
      - DEPOSIT_RPC_URL
      - DEPOSIT_CONTRACT_ADDRESS
      - USE_VALIDATOR=${USE_VALIDATOR:-false}
    command: /vana/container-scripts/check-config.sh
    depends_on:
      geth-init:
        condition: service_completed_successfully
      jwt-gen:
        condition: service_completed_successfully
      prysm-keygen:
        condition: service_completed_successfully
    profiles: ["init", "node", "validator", "manual"]
    secrets:
      - account_password
      - deposit_private_key
      - wallet_password

  # Main node services
  geth:
    <<: *default-logging
    image: ethereum/client-go:${GETH_VERSION:-latest}
    container_name: geth
    volumes:
      - ./data/execution:/root/.ethereum  # Use the default so that the default ipc path works, etc.
      - ./data/jwt.hex:/root/.ethereum/jwt.hex:ro
    ports:
      # Do not expose the auth RPC port used by the beacon node
      #- "${AUTHRPC_PORT:-8551}:${AUTHRPC_PORT:-8551}"
      - "${P2P_PORT:-30303}:${P2P_PORT:-30303}"
      # Expose HTTP RPC on port 8545 to the host only
      - "127.0.0.1:${HTTP_PORT:-8545}:${HTTP_PORT:-8545}"
      # Or, if you want to make your API public, use this:
      # - "${HTTP_PORT:-8545}:${HTTP_PORT:-8545}"
    command:
      - --verbosity=3  # 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail
      - --networkid=${CHAIN_ID}
      - --datadir=/root/.ethereum
      - --nat=extip:${EXTERNAL_IP}
      - --port=${P2P_PORT:-30303}
      - --syncmode=${GETH_SYNCMODE:-full}
      - --state.scheme=${GETH_STATE_SCHEME:-path}
      - --gcmode=${GETH_GCMODE:-full}
      - --bootnodes=${GETH_BOOTNODES}
      # Enable HTTP RPC, available at http://host:${HTTP_PORT:-8545}
      # If you want to limit access to certain IPs, use --http.corsdomain="..." and --http.vhosts="..."
      - --http
      - --http.vhosts=${GETH_HTTP_VHOSTS:-*}
      - --http.addr=0.0.0.0
      - --http.port=${HTTP_PORT:-8545}
      - --http.api=eth,net,web3
      # Only enable personal and admin APIs if you know what you're doing
      # - --http.api=eth,net,web3,personal,admin
      - --rpc.txfeecap=${GETH_RPC_TXFEECAP:-1000}
      # Enable the auth RPC API for the beacon node
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=${AUTHRPC_PORT:-8551}
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.vhosts=*
      - --nodekey=/root/.ethereum/bootnode.key
    depends_on:
      geth-init:
        condition: service_completed_successfully
      jwt-gen:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
      bootnode-init:
        condition: service_completed_successfully
    profiles: ["node", "validator"]

  beacon:
    <<: *default-logging
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_VERSION:-latest}
    container_name: beacon
    volumes:
      - ./data/jwt.hex:/vana/jwt.hex:ro
      - ./data/consensus:/vana/consensus
      - ./networks/${NETWORK}/genesis.ssz:/vana/consensus/genesis.ssz:ro
      - ./networks/${NETWORK}/config.yml:/vana/consensus/config.yml:ro
    ports:
      # Do not expose the RPC port used by the validator
      # - "${RPC_PORT:-4000}:${RPC_PORT:-4000}"
      # Expose the gRPC gateway on port 3500 to the host only
      - "127.0.0.1:${GRPC_GATEWAY_PORT:-3500}:${GRPC_GATEWAY_PORT:-3500}"
      # Or, if you want to make your API public, use this:
      # - "${GRPC_GATEWAY_PORT:-3500}:${GRPC_GATEWAY_PORT:-3500}"
      - "${P2P_TCP_PORT:-13000}:${P2P_TCP_PORT:-13000}"
      - "${P2P_UDP_PORT:-12000}:${P2P_UDP_PORT:-12000}/udp"
    environment:
      - WITHDRAWAL_ADDRESS
      - PRYSM_SLOTS_PER_ARCHIVE_POINT
      - PRYSM_BLOCK_BATCH_LIMIT
      - PRYSM_BLOCK_BATCH_LIMIT_BURST_FACTOR
      - PRYSM_BLOB_BATCH_LIMIT
      - PRYSM_BLOB_BATCH_LIMIT_BURST_FACTOR
    command:
      # TODO: To use checkpoint sync, uncomment these lines and ensure that TRUSTED_BEACON_NODE_URL and WEAK_SUBJECTIVITY_CHECKPOINT are set in your .env file
      #- --weak-subjectivity-checkpoint=${WEAK_SUBJECTIVITY_CHECKPOINT}
      #- --checkpoint-sync-url=${TRUSTED_BEACON_NODE_URL}
      #- --genesis-beacon-api-url=${TRUSTED_BEACON_NODE_URL}  # not strictly necessary, genesis state is provided by this repo
      - --accept-terms-of-use
      - --chain-id=${CHAIN_ID}
      - --verbosity=info
      - --min-sync-peers=1
      - --block-batch-limit=${PRYSM_BLOCK_BATCH_LIMIT:-256}
      - --block-batch-limit-burst-factor=${PRYSM_BLOCK_BATCH_LIMIT_BURST_FACTOR:-8}
      - --blob-batch-limit=${PRYSM_BLOB_BATCH_LIMIT:-256}
      - --blob-batch-limit-burst-factor=${PRYSM_BLOB_BATCH_LIMIT_BURST_FACTOR:-8}
      - --datadir=/vana/consensus/beacondata
      - --genesis-state=/vana/consensus/genesis.ssz
      - --chain-config-file=/vana/consensus/config.yml
      - --execution-endpoint=http://geth:${AUTHRPC_PORT:-8551}
      - --jwt-secret=/vana/jwt.hex
      - --rpc-host=0.0.0.0
      - --rpc-port=${RPC_PORT:-4000}
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=${GRPC_GATEWAY_PORT:-3500}
      - --p2p-host-ip=${EXTERNAL_IP}
      - --bootstrap-node=${PRYSM_PEER_1}
      - --peer=${PRYSM_PEER_1}
      - --peer=${PRYSM_PEER_2}
      - --peer=${PRYSM_PEER_3}
      - --peer=${PRYSM_PEER_4}
      - --peer=${PRYSM_PEER_5}
      - --peer=${PRYSM_PEER_6}
      - --peer=${PRYSM_PEER_7}
      - --peer=${PRYSM_PEER_8}
      - --peer=${PRYSM_PEER_9}
      - --peer=${PRYSM_PEER_10}
      # Add more peers as needed, make sure to add them to .env
      - --p2p-static-id
      - --p2p-priv-key=/vana/consensus/prysm-key.hex
      - --suggested-fee-recipient=${WITHDRAWAL_ADDRESS}
      - --slots-per-archive-point=${PRYSM_SLOTS_PER_ARCHIVE_POINT:-512}
    depends_on:
      geth:
        condition: service_started
      prysm-keygen:
        condition: service_completed_successfully
      jwt-gen:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
    profiles: ["node", "validator"]

  # Validator services
  validator-keygen:
    <<: *default-logging
    build:
      context: https://github.com/vana-com/staking-deposit-cli.git#vana-main
      dockerfile: Dockerfile
    container_name: validator-setup
    volumes:
      - ./secrets:/app/validator_keys
      - ./container-scripts:/vana/container-scripts
    environment:
      - NUM_VALIDATORS
      - WITHDRAWAL_ADDRESS
      - NETWORK
      - LANGUAGE
    entrypoint: "/vana/container-scripts/validator-keygen.sh"
    profiles: ["manual"]

  validator-import:
    <<: *default-logging
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION:-latest}
    container_name: validator-import
    volumes:
      # For now, continue to mount this for --keys-dir.
      # In the future it would be better to manage keys and deposit data apart from secrets/.
      - ./secrets:/vana/secrets:ro
      - ./data/validator/wallet:/vana/wallet
    command:
      - accounts
      - import
      - --accept-terms-of-use
      - --keys-dir=/vana/secrets
      - --wallet-dir=/vana/wallet
      - --account-password-file=/run/secrets/account_password
      - --wallet-password-file=/run/secrets/wallet_password
    secrets:
      - account_password
      - wallet_password
    # Re-enable if validator-keygen can be automated
    # depends_on:
    #   validator-keygen:
    #     condition: service_completed_successfully
    profiles: ["manual", "validator"]

  validator:
    <<: *default-logging
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION:-latest}
    container_name: validator
    volumes:
      - ./data/validator:/vana/validator
      - ./data/validator/wallet:/vana/wallet
      - ./networks/${NETWORK}/config.yml:/vana/consensus/config.yml:ro
    environment:
      - WITHDRAWAL_ADDRESS
    command:
      - --accept-terms-of-use
      - --verbosity=info
      # TODO: In prior testing, beacon didn't seem to work when ${EXTERNAL_IP} did. Check if this is still the case.
      - --beacon-rpc-provider=beacon:${RPC_PORT:-4000}
      #- --beacon-rpc-provider=${EXTERNAL_IP}:${RPC_PORT:-4000}
      - --beacon-rest-api-provider=${EXTERNAL_IP}:${RPC_PORT:-4000}
      - --datadir=/vana/validator
      - --wallet-dir=/vana/wallet
      - --wallet-password-file=/run/secrets/wallet_password
      - --chain-config-file=/vana/consensus/config.yml
      - --suggested-fee-recipient=${WITHDRAWAL_ADDRESS}
    depends_on:
      beacon:
        condition: service_started
      validator-import:
        condition: service_completed_successfully
      check-config:
        condition: service_completed_successfully
    secrets:
      - wallet_password
    profiles: ["validator"]

  submit-deposits:
    <<: *default-logging
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: submit-deposits
    volumes:
      - ./secrets:/validator_keys:ro
    environment:
      - DEPOSIT_RPC_URL
      - DEPOSIT_CONTRACT_ADDRESS
    entrypoint: ["sh", "-c"]
    command:
      - |
        apk add --no-cache --quiet jq
        for file in /validator_keys/deposit_data-*.json; do
          PUBKEY=$(jq -r '.[0].pubkey' "$$file")
          WITHDRAWAL_CREDENTIALS=$(jq -r '.[0].withdrawal_credentials' "$$file")
          SIGNATURE=$(jq -r '.[0].signature' "$$file")
          DEPOSIT_DATA_ROOT=$(jq -r '.[0].deposit_data_root' "$$file")
          cast send $$DEPOSIT_CONTRACT_ADDRESS \
            "deposit(bytes,bytes,bytes,bytes32)" \
            "0x$$PUBKEY" \
            "0x$$WITHDRAWAL_CREDENTIALS" \
            "0x$$SIGNATURE" \
            "0x$$DEPOSIT_DATA_ROOT" \
            --value 35000ether \
            --private-key-file /run/secrets/deposit_private_key \
            --rpc-url $$DEPOSIT_RPC_URL
        done
    depends_on:
      check-config:
        condition: service_completed_successfully
      validator-import:
        condition: service_completed_successfully
    profiles: ["manual"]
    secrets:
      - deposit_private_key

  # Cleanup services
  delete-all:
    <<: *default-logging
    container_name: delete-all
    image: alpine:latest
    command: echo "All data deleted"
    depends_on:
      delete-geth:
        condition: service_completed_successfully
      delete-beacon:
        condition: service_completed_successfully
    profiles: ["delete"]

  delete-geth:
    <<: *default-logging
    container_name: delete-geth
    image: alpine:latest
    command: rm -rf /vana/execution/geth
    volumes:
      - ./data/geth:/vana/execution
    profiles: ["delete"]

  delete-beacon:
    <<: *default-logging
    container_name: delete-prysm
    image: alpine:latest
    command: rm -rf /vana/consensus/beacondata
    volumes:
      - ./data/consensus:/vana/consensus
    profiles: ["delete"]

  # Be careful with this one, it will delete slashing protection in validator.db
  # https://docs.prylabs.network/docs/wallet/slashing-protection
  delete-validator:
    <<: *default-logging
    container_name: delete-validator
    image: alpine:latest
    command: rm -rf /vana/validator
    volumes:
      - ./data/validator:/vana/validator
    profiles: ["delete"]

secrets:
  deposit_private_key:
    file: ./secrets/deposit_private_key.txt
  wallet_password:
    file: ./secrets/wallet_password.txt
  account_password:
    file: ./secrets/account_password.txt