PRESET_BASE: mainnet
TERMINAL_TOTAL_DIFFICULTY: "280"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: "18446744073709551615"
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: "128"
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: "1"
MIN_GENESIS_TIME: "1727298095"
GENESIS_FORK_VERSION: "0x20000089"
GENESIS_DELAY: "120"
ALTAIR_FORK_VERSION: "0x20000090"
ALTAIR_FORK_EPOCH: "1"
BELLATRIX_FORK_VERSION: "0x20000091"
BELLATRIX_FORK_EPOCH: "2"
SECONDS_PER_SLOT: "3"
SECONDS_PER_ETH1_BLOCK: "3"
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: "256"
SHARD_COMMITTEE_PERIOD: "256"
ETH1_FOLLOW_DISTANCE: "1"
INACTIVITY_SCORE_BIAS: "4"
INACTIVITY_SCORE_RECOVERY_RATE: "16"
EJECTION_BALANCE: "16000000000"
MIN_PER_EPOCH_CHURN_LIMIT: "4"
CHURN_LIMIT_QUOTIENT: "32"
PROPOSER_SCORE_BOOST: "40"
DEPOSIT_CHAIN_ID: "616161"
DEPOSIT_NETWORK_ID: "616161"
DEPOSIT_CONTRACT_ADDRESS: "0x17bbe91c315bf14f38f6d35052a827cadffe184e"
