CONFIG_NAME: vana
PRESET_BASE: mainnet
TERMINAL_TOTAL_DIFFICULTY: "1200"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: "18446744073709551615"
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: "128"
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: "3"
MIN_GENESIS_TIME: "0"
GENESIS_FORK_VERSION: "0x20000089"
GENESIS_DELAY: "15"
ALTAIR_FORK_VERSION: "0x20000090"
ALTAIR_FORK_EPOCH: "1"
BELLATRIX_FORK_VERSION: "0x20000091"
BELLATRIX_FORK_EPOCH: "2"
SECONDS_PER_SLOT: "6"
SECONDS_PER_ETH1_BLOCK: "6"
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: "256"
SHARD_COMMITTEE_PERIOD: "256"
ETH1_FOLLOW_DISTANCE: "64"
INACTIVITY_SCORE_BIAS: "4"
INACTIVITY_SCORE_RECOVERY_RATE: "16"
EJECTION_BALANCE: "17500000000000"
MIN_PER_EPOCH_CHURN_LIMIT: "2"
CHURN_LIMIT_QUOTIENT: "42"
DEPOSIT_CHAIN_ID: "1480"
DEPOSIT_NETWORK_ID: "1480"
DEPOSIT_CONTRACT_ADDRESS: "0x17bbe91c315bf14f38f6d35052a827cadffe184e"
